id: P003137
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG24986
  title: གནམ་སྔོན་པོ་ས་དམར་པོ།
  author: ''
  volumes:
    9878ab7118c7476492f32f3edd955d15:
      image_group_id: I1KG24988
      title: ''
      volume_number: 1
      total_pages: 51
      base_file: v001.txt
